.Dd $Mdocdate$
.Dt fortune 1
.Os
.Sh NAME
.Nm fortune
.Nd output random quip
.Sh SYNOPSIS
.Nm
.Ar fn
.Sh DESCRIPTION
For all BSD-style fortune files
.Ar fn ,
.Nm
selects a random quip from BSD fortune file
.Ar fn
and writes this entry to the standard output.
.Sh AUTHORS
This program is maintained by
.An Varik Valefor
.Aq varikvalefor@aol.com .
